### PR TITLE
add instasmail.com, yousmail.com, smailpro.com, hatmail.ir

### PR DESCRIPTION
**Pull request by payam124**
instasmail.com and  yousmail.com are both from smailpro.com

### CODE REVIEW

**Comment by martenson** [comment]
This one is a pickle, since smailpro.com seems to automate gmail registration as a disposable email service (I got addresses like `clinicpainfu.l36.8.3@gmail.com`. This is surely abuse of google service and should be reported upstream. 

What do @di and @deguif think?

**Comment by di** [comment]
Does it actually work? I wasn't able to get it to receive a message to a `@gmail.com` address it generated.

**Comment by martenson** [comment]
I tested it with guerillamail and received the message fine :/

Advanced

**Comment by martenson** [comment]
This might be a form to use for reporting gmail abuse:
https://support.google.com/mail/contact/abuse

**Comment by Mis012** [comment]
can confirm that smailpro.com works nicely to avoid stupid login walls, thanks for the tip :)

**Comment by martenson** [comment]
@Mis012 just be careful about who reads your mail ;)

**Pull request closed without merging**
