### PR TITLE
Update disposable_email_blocklist.conf

### PR DESCRIPTION
**Pull request by zhangjiayin**

### CODE REVIEW

**Comment by zhangjiayin** [comment]
add freemailzone.com

**Comment by martenson** [comment]
@zhangjiayin thanks for the contribution, please run the maintain.sh script to properly order the list.

**Comment by zhangjiayin** [comment]
OK I will reopen an issue for it 
Thank you.

**Comment by zhangjiayin** [comment]
https://github.com/disposable-email-domains/disposable-email-domains/pull/336

**Pull request closed without merging**
