### PR TITLE
feat: domains from 2022-02-14

### PR DESCRIPTION
**Pull request by russorat**
foreastate.com - https://www.mailcheck.ai/domain/foreastate.com - https://www.fakemail.net/
vixtricks.com - https://www.mailcheck.ai/domain/vixtricks.com - https://temp-mail.org/ - 164.90.252.249
sheryli.com - https://www.mailcheck.ai/domain/sheryli.com - https://temp-mail.org/ - 164.90.252.249
appzily.com - https://www.mailcheck.ai/domain/appzily.com - https://temp-mail.io/en/
cashflow35.com - https://www.mailcheck.ai/domain/cashflow35.com - https://temp-mail.io/en/

cloud-mail.top - https://temp-mail.io/en/
mac-24.com - https://temp-mail.io/en/
thejoker5.com - https://temp-mail.io/en/
greencafe24.com - https://temp-mail.io/en/
crepeau12.com - https://temp-mail.io/en/
appzily.com - https://temp-mail.io/en/
coffeetimer24.com - https://temp-mail.io/en/
popcornfarm7.com - https://temp-mail.io/en/
bestparadize.com - https://temp-mail.io/en/
kjkszpjcompany.com - https://temp-mail.io/en/
cashflow35.com - https://temp-mail.io/en/
crossmailjet.com - https://temp-mail.io/en/
kobrandly.com - https://temp-mail.io/en/
blondemorkin.com - https://temp-mail.io/en/
block521.com - https://temp-mail.io/en/
best-john-boats.com - https://temp-mail.io/en/
popcornfly.com - https://temp-mail.io/en/

### CODE REVIEW

**Comment by russorat** [comment]
added:

labworld.org - https://cryptogmail.com/
mentonit.net - https://embedded.cryptogmail.com/
vintomaper.com - https://embedded.cryptogmail.com/

**Comment by russorat** [comment]
bump

**Comment by martenson** [comment]
Thanks @russorat, sorry for the delays, world is upside down.

**Comment by russorat** [comment]
Thank you! I hope you and your loved ones stay safe.

**Pull request merged**
