### PR TITLE
update disposable email blocklist

### PR DESCRIPTION
**Pull request by chirzul**
44oe.tech
afdan.site
afdan.store
airsmtp.com
andri.store
aniross.com
apmail.org
aprte.com
arull.tech
bekhetr.com
butyusa.com
casibwair.net
catbar.net
cdaixin.com
chairul.tech
connati.com
cslongs.site
diwark.com
dogsmot.com
doveify.com
dulanfs.com
duobp.com
ekostore.store
ezblog.co
f5.si
gmail10p.com
hafid.store
hasdfr.tech
idemainc.com
jekeb.com
kissypie.com
mamuy.com
notenote.tech
oemails.com
oinstyle.com
oletters.com
onialtd.com
ostinmail.com
picork.com
pixatate.com
ponp.be
pstorai.com
raknife.com
seazyc.store
sendapp.uk
shasto.com
sitbam.com
suiemail.com
suseb.com
tactar.com
taiwea.com
techkotek.com
voewo.com
wenda.store
wwtake.com
xagym.com
xanalx.com
xfrivaldi.store
xsend.org
yeswep.com
yomdi.com
zirafyn.com

### CODE REVIEW

**Comment by martenson** [comment]
Specifically, please cite in your PR where one can generate a disposable email address which uses that domain, so the maintainers can verify it.

**Comment by chirzul** [comment]
> Specifically, please cite in your PR where one can generate a disposable email address which uses that domain, so the maintainers can verify it.

I got these domains from big data at the company where I work. There are a total of 119 domains. I want to use this library but only 57 domains have been registered here.

**Comment by kirylrb** [comment]
Please add emailcbox.pro

**Comment by martenson** [comment]
@chirzul the fact you got it from somewhere does not really prove these are disposable. What were the metrics considered when you identified them at your company?

**Pull request closed without merging**
