### PR TITLE
Update disposable_email_blocklist.conf

### PR DESCRIPTION
**Pull request by kirylrb**
https://github.com/disposable-email-domains/disposable-email-domains/issues/486

https://www.ipqualityscore.com/domain-reputation/emailcbox.pro

My site is full of fake users from this domain who are attempting to parse the content.

Screenshot 2024-06-24 at 15 34 10

### CODE REVIEW

**Comment by kirylrb** [comment]
@martenson ^^

**Comment by kirylrb** [comment]
@joelweinberger  ^^

**Comment by joelweinberger** [comment]
I am not a maintainer of this repo—I just happened to make a contribution as well :-) I think @martenson is a reviewer, though.

**Comment by martenson** [comment]
thank you @kirylrb !

**Pull request merged**
